//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.stix.extensions.identity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.stix.common_1.IdentityType;


/**
 * The CIQIdentity3.0InstanceType provides an extension to the IdentityStructureAbstractType which imports and leverages version 3.0 of the OASIS CIQ-PIL schema for structured characterization of Identities.
 * 
 * <p>Java class for CIQIdentity3.0InstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIQIdentity3.0InstanceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://stix.mitre.org/common-1}IdentityType">
 *       &lt;sequence>
 *         &lt;element name="Specification" type="{http://stix.mitre.org/extensions/Identity#CIQIdentity3.0-1}STIXCIQIdentity3.0Type"/>
 *         &lt;element name="Role" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIQIdentity3.0InstanceType", propOrder = {
    "specification",
    "role"
})
public class CIQIdentity30InstanceType
    extends IdentityType
{

    @XmlElement(name = "Specification", required = true)
    protected STIXCIQIdentity30Type specification;
    @XmlElement(name = "Role")
    protected List<String> role;

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link STIXCIQIdentity30Type }
     *     
     */
    public STIXCIQIdentity30Type getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link STIXCIQIdentity30Type }
     *     
     */
    public void setSpecification(STIXCIQIdentity30Type value) {
        this.specification = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the role property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRole() {
        if (role == null) {
            role = new ArrayList<String>();
        }
        return this.role;
    }

}
