//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.stix.extensions.testmechanism;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.mitre.stix.common_1.ControlledVocabularyStringType;
import org.mitre.stix.common_1.EncodedCDATAType;
import org.mitre.stix.common_1.StructuredTextType;
import org.mitre.stix.indicator_2.TestMechanismType;


/**
 * The GenericTestMechanismType specifies an instantial extension from the abstract TestMechanismType intended to support the generic inclusion of any test mechanism content.
 * 
 * <p>Java class for GenericTestMechanismType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericTestMechanismType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://stix.mitre.org/Indicator-2}TestMechanismType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://stix.mitre.org/common-1}StructuredTextType"/>
 *         &lt;element name="Type" type="{http://stix.mitre.org/common-1}ControlledVocabularyStringType"/>
 *         &lt;element name="Specification" type="{http://stix.mitre.org/common-1}EncodedCDATAType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="reference_location" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericTestMechanismType", propOrder = {
    "description",
    "type",
    "specification"
})
public class GenericTestMechanismType
    extends TestMechanismType
{

    @XmlElement(name = "Description", required = true)
    protected StructuredTextType description;
    @XmlElement(name = "Type", required = true)
    protected ControlledVocabularyStringType type;
    @XmlElement(name = "Specification", required = true)
    protected EncodedCDATAType specification;
    @XmlAttribute(name = "reference_location")
    @XmlSchemaType(name = "anyURI")
    protected String referenceLocation;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link StructuredTextType }
     *     
     */
    public StructuredTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructuredTextType }
     *     
     */
    public void setDescription(StructuredTextType value) {
        this.description = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledVocabularyStringType }
     *     
     */
    public ControlledVocabularyStringType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledVocabularyStringType }
     *     
     */
    public void setType(ControlledVocabularyStringType value) {
        this.type = value;
    }

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedCDATAType }
     *     
     */
    public EncodedCDATAType getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedCDATAType }
     *     
     */
    public void setSpecification(EncodedCDATAType value) {
        this.specification = value;
    }

    /**
     * Gets the value of the referenceLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceLocation() {
        return referenceLocation;
    }

    /**
     * Sets the value of the referenceLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceLocation(String value) {
        this.referenceLocation = value;
    }

}
