//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.stix.extensions.testmechanism;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.oval.xmlschema.oval_definitions_5.OvalDefinitions;
import org.mitre.oval.xmlschema.oval_variables_5.OvalVariables;
import org.mitre.stix.indicator_2.TestMechanismType;


/**
 * The OVALTestMechanismType provides an extension to the TestMechanismType which imports and leverages the OVAL schema in order to include OVAL Definitions as the test mechanism.
 * 
 * <p>Java class for OVAL5.10TestMechanismType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OVAL5.10TestMechanismType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://stix.mitre.org/Indicator-2}TestMechanismType">
 *       &lt;sequence>
 *         &lt;element ref="{http://oval.mitre.org/XMLSchema/oval-definitions-5}oval_definitions"/>
 *         &lt;element ref="{http://oval.mitre.org/XMLSchema/oval-variables-5}oval_variables" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OVAL5.10TestMechanismType", namespace = "http://stix.mitre.org/extensions/TestMechanism#OVAL5.10-1", propOrder = {
    "ovalDefinitions",
    "ovalVariables"
})
public class OVAL510TestMechanismType
    extends TestMechanismType
{

    @XmlElement(name = "oval_definitions", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", required = true)
    protected OvalDefinitions ovalDefinitions;
    @XmlElement(name = "oval_variables", namespace = "http://oval.mitre.org/XMLSchema/oval-variables-5")
    protected OvalVariables ovalVariables;

    /**
     * The oval_definitions field contains the structured specification of the OVAL test mechanism. When including OVAL Definition documents it is expected that at least one valid OVAL Definition Definition is included.
     * 
     * @return
     *     possible object is
     *     {@link OvalDefinitions }
     *     
     */
    public OvalDefinitions getOvalDefinitions() {
        return ovalDefinitions;
    }

    /**
     * Sets the value of the ovalDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OvalDefinitions }
     *     
     */
    public void setOvalDefinitions(OvalDefinitions value) {
        this.ovalDefinitions = value;
    }

    /**
     * The oval_variables field contains a valid OVAL Variables document and should only be used to supply external variable values needed by this OVAL Test Mechanism's OVAL Definitions.
     * 
     * @return
     *     possible object is
     *     {@link OvalVariables }
     *     
     */
    public OvalVariables getOvalVariables() {
        return ovalVariables;
    }

    /**
     * Sets the value of the ovalVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link OvalVariables }
     *     
     */
    public void setOvalVariables(OvalVariables value) {
        this.ovalVariables = value;
    }

}
