//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.stix.extensions.testmechanism;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.stix.common_1.EncodedCDATAType;
import org.mitre.stix.indicator_2.TestMechanismType;


/**
 * The SnortTestMechanismType specifies an instantial extension from the abstract TestMechanismType intended to support the inclusion of a Snort rule as a test mechanism content.
 * 
 * <p>Java class for SnortTestMechanismType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SnortTestMechanismType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://stix.mitre.org/Indicator-2}TestMechanismType">
 *       &lt;sequence>
 *         &lt;element name="Product_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Rule" type="{http://stix.mitre.org/common-1}EncodedCDATAType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Event_Filter" type="{http://stix.mitre.org/common-1}EncodedCDATAType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Rate_Filter" type="{http://stix.mitre.org/common-1}EncodedCDATAType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Event_Suppression" type="{http://stix.mitre.org/common-1}EncodedCDATAType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SnortTestMechanismType", namespace = "http://stix.mitre.org/extensions/TestMechanism#Snort-1", propOrder = {
    "productName",
    "version",
    "rule",
    "eventFilter",
    "rateFilter",
    "eventSuppression"
})
public class SnortTestMechanismType
    extends TestMechanismType
{

    @XmlElement(name = "Product_Name")
    protected String productName;
    @XmlElement(name = "Version")
    protected String version;
    @XmlElement(name = "Rule")
    protected List<EncodedCDATAType> rule;
    @XmlElement(name = "Event_Filter")
    protected List<EncodedCDATAType> eventFilter;
    @XmlElement(name = "Rate_Filter")
    protected List<EncodedCDATAType> rateFilter;
    @XmlElement(name = "Event_Suppression")
    protected List<EncodedCDATAType> eventSuppression;

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EncodedCDATAType }
     * 
     * 
     */
    public List<EncodedCDATAType> getRule() {
        if (rule == null) {
            rule = new ArrayList<EncodedCDATAType>();
        }
        return this.rule;
    }

    /**
     * Gets the value of the eventFilter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventFilter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EncodedCDATAType }
     * 
     * 
     */
    public List<EncodedCDATAType> getEventFilter() {
        if (eventFilter == null) {
            eventFilter = new ArrayList<EncodedCDATAType>();
        }
        return this.eventFilter;
    }

    /**
     * Gets the value of the rateFilter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rateFilter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRateFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EncodedCDATAType }
     * 
     * 
     */
    public List<EncodedCDATAType> getRateFilter() {
        if (rateFilter == null) {
            rateFilter = new ArrayList<EncodedCDATAType>();
        }
        return this.rateFilter;
    }

    /**
     * Gets the value of the eventSuppression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventSuppression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventSuppression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EncodedCDATAType }
     * 
     * 
     */
    public List<EncodedCDATAType> getEventSuppression() {
        if (eventSuppression == null) {
            eventSuppression = new ArrayList<EncodedCDATAType>();
        }
        return this.eventSuppression;
    }

}
