//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.stix.extensions.testmechanism;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.stix.common_1.EncodedCDATAType;
import org.mitre.stix.indicator_2.TestMechanismType;


/**
 * The YaraTestMechanismType specifies an instantial extension from the abstract TestMechanismType intended to support the inclusion of a YARA rule as a test mechanism content.
 * 
 * <p>Java class for YaraTestMechanismType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="YaraTestMechanismType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://stix.mitre.org/Indicator-2}TestMechanismType">
 *       &lt;sequence>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Rule" type="{http://stix.mitre.org/common-1}EncodedCDATAType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "YaraTestMechanismType", namespace = "http://stix.mitre.org/extensions/TestMechanism#YARA-1", propOrder = {
    "version",
    "rule"
})
public class YaraTestMechanismType
    extends TestMechanismType
{

    @XmlElement(name = "Version")
    protected String version;
    @XmlElement(name = "Rule")
    protected EncodedCDATAType rule;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedCDATAType }
     *     
     */
    public EncodedCDATAType getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedCDATAType }
     *     
     */
    public void setRule(EncodedCDATAType value) {
        this.rule = value;
    }

}
