//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.common_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.mitre.cybox.objects.APIObjectType;
import org.mitre.cybox.objects.ARPCacheObjectType;
import org.mitre.cybox.objects.ASObjectType;
import org.mitre.cybox.objects.AccountObjectType;
import org.mitre.cybox.objects.AddressObjectType;
import org.mitre.cybox.objects.ArtifactObjectType;
import org.mitre.cybox.objects.CodeObjectType;
import org.mitre.cybox.objects.CustomObjectType;
import org.mitre.cybox.objects.DNSCacheObjectType;
import org.mitre.cybox.objects.DNSQueryObjectType;
import org.mitre.cybox.objects.DNSRecordObjectType;
import org.mitre.cybox.objects.DeviceObjectType;
import org.mitre.cybox.objects.DiskObjectType;
import org.mitre.cybox.objects.DiskPartitionObjectType;
import org.mitre.cybox.objects.DomainNameObjectType;
import org.mitre.cybox.objects.EmailMessageObjectType;
import org.mitre.cybox.objects.FileObjectType;
import org.mitre.cybox.objects.GUIObjectType;
import org.mitre.cybox.objects.HTTPSessionObjectType;
import org.mitre.cybox.objects.HostnameObjectType;
import org.mitre.cybox.objects.LibraryObjectType;
import org.mitre.cybox.objects.LinuxPackageObjectType;
import org.mitre.cybox.objects.MemoryObjectType;
import org.mitre.cybox.objects.MutexObjectType;
import org.mitre.cybox.objects.NetRouteObjectType;
import org.mitre.cybox.objects.NetworkConnectionObjectType;
import org.mitre.cybox.objects.NetworkFlowObjectType;
import org.mitre.cybox.objects.NetworkPacketObjectType;
import org.mitre.cybox.objects.NetworkRouteEntryObjectType;
import org.mitre.cybox.objects.NetworkSocketObjectType;
import org.mitre.cybox.objects.NetworkSubnetObjectType;
import org.mitre.cybox.objects.PipeObjectType;
import org.mitre.cybox.objects.PortObjectType;
import org.mitre.cybox.objects.ProcessObjectType;
import org.mitre.cybox.objects.ProductObjectType;
import org.mitre.cybox.objects.SMSMessageObjectType;
import org.mitre.cybox.objects.SemaphoreObjectType;
import org.mitre.cybox.objects.SocketAddressObjectType;
import org.mitre.cybox.objects.SystemObjectType;
import org.mitre.cybox.objects.URIObjectType;
import org.mitre.cybox.objects.URLHistoryObjectType;
import org.mitre.cybox.objects.UserSessionObjectType;
import org.mitre.cybox.objects.VolumeObjectType;
import org.mitre.cybox.objects.WhoisObjectType;
import org.mitre.cybox.objects.WindowsCriticalSectionObjectType;
import org.mitre.cybox.objects.WindowsEventLogObjectType;
import org.mitre.cybox.objects.WindowsEventObjectType;
import org.mitre.cybox.objects.WindowsFilemappingObjectType;
import org.mitre.cybox.objects.WindowsHandleObjectType;
import org.mitre.cybox.objects.WindowsHookObjectType;
import org.mitre.cybox.objects.WindowsKernelHookObjectType;
import org.mitre.cybox.objects.WindowsKernelObjectType;
import org.mitre.cybox.objects.WindowsMailslotObjectType;
import org.mitre.cybox.objects.WindowsNetworkShareObjectType;
import org.mitre.cybox.objects.WindowsPrefetchObjectType;
import org.mitre.cybox.objects.WindowsRegistryKeyObjectType;
import org.mitre.cybox.objects.WindowsSystemRestoreObjectType;
import org.mitre.cybox.objects.WindowsTaskObjectType;
import org.mitre.cybox.objects.WindowsThreadObjectType;
import org.mitre.cybox.objects.WindowsWaitableTimerObjectType;
import org.mitre.cybox.objects.X509CertificateObjectType;


/**
 * The ObjectPropertiesType is an Abstract type placeholder within the CybOX schema enabling the inclusion of contextually varying object properties descriptions. This Abstract type is leveraged as the extension base for all predefined CybOX object properties schemas. Through this extension mechanism any object instance data based on an object properties schema extended from ObjectPropertiesType (e.g. File_Object, Address_Object, etc.) can be directly integrated into any instance document where a field is defined as ObjectPropertiesType. For flexibility and extensibility purposes any user of CybOX can specify their own externally defined object properties schemas (outside of or derived from the set of predefined objects) extended from ObjectPropertiesType and utilize them as part of their CybOX content.
 * 
 * <p>Java class for ObjectPropertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectPropertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Custom_Properties" type="{http://cybox.mitre.org/common-2}CustomPropertiesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="object_reference" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectPropertiesType", propOrder = {
    "customProperties"
})
@XmlSeeAlso({
    WindowsWaitableTimerObjectType.class,
    WindowsHandleObjectType.class,
    NetRouteObjectType.class,
    AddressObjectType.class,
    DeviceObjectType.class,
    WindowsNetworkShareObjectType.class,
    PortObjectType.class,
    ArtifactObjectType.class,
    CustomObjectType.class,
    MemoryObjectType.class,
    WindowsKernelHookObjectType.class,
    SemaphoreObjectType.class,
    NetworkPacketObjectType.class,
    WindowsRegistryKeyObjectType.class,
    ProductObjectType.class,
    NetworkConnectionObjectType.class,
    HTTPSessionObjectType.class,
    DNSQueryObjectType.class,
    DNSRecordObjectType.class,
    SocketAddressObjectType.class,
    HostnameObjectType.class,
    URLHistoryObjectType.class,
    WhoisObjectType.class,
    DomainNameObjectType.class,
    WindowsSystemRestoreObjectType.class,
    WindowsCriticalSectionObjectType.class,
    WindowsEventLogObjectType.class,
    ARPCacheObjectType.class,
    CodeObjectType.class,
    WindowsKernelObjectType.class,
    WindowsPrefetchObjectType.class,
    VolumeObjectType.class,
    WindowsThreadObjectType.class,
    LinuxPackageObjectType.class,
    DNSCacheObjectType.class,
    UserSessionObjectType.class,
    LibraryObjectType.class,
    DiskObjectType.class,
    DiskPartitionObjectType.class,
    WindowsTaskObjectType.class,
    EmailMessageObjectType.class,
    WindowsEventObjectType.class,
    SystemObjectType.class,
    NetworkSubnetObjectType.class,
    GUIObjectType.class,
    URIObjectType.class,
    PipeObjectType.class,
    AccountObjectType.class,
    WindowsMailslotObjectType.class,
    WindowsFilemappingObjectType.class,
    NetworkRouteEntryObjectType.class,
    FileObjectType.class,
    ProcessObjectType.class,
    NetworkSocketObjectType.class,
    ASObjectType.class,
    SMSMessageObjectType.class,
    NetworkFlowObjectType.class,
    APIObjectType.class,
    X509CertificateObjectType.class,
    MutexObjectType.class,
    WindowsHookObjectType.class
})
public abstract class ObjectPropertiesType {

    @XmlElement(name = "Custom_Properties")
    protected CustomPropertiesType customProperties;
    @XmlAttribute(name = "object_reference")
    protected QName objectReference;

    /**
     * Gets the value of the customProperties property.
     * 
     * @return
     *     possible object is
     *     {@link CustomPropertiesType }
     *     
     */
    public CustomPropertiesType getCustomProperties() {
        return customProperties;
    }

    /**
     * Sets the value of the customProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomPropertiesType }
     *     
     */
    public void setCustomProperties(CustomPropertiesType value) {
        this.customProperties = value;
    }

    /**
     * Gets the value of the objectReference property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getObjectReference() {
        return objectReference;
    }

    /**
     * Sets the value of the objectReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setObjectReference(QName value) {
        this.objectReference = value;
    }

}
