//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.data_marking.extensions.markingstructure;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TLPColorEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TLPColorEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RED"/>
 *     &lt;enumeration value="AMBER"/>
 *     &lt;enumeration value="GREEN"/>
 *     &lt;enumeration value="WHITE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TLPColorEnum")
@XmlEnum
public enum TLPColorEnum {

    RED,
    AMBER,
    GREEN,
    WHITE;

    public String value() {
        return name();
    }

    public static TLPColorEnum fromValue(String v) {
        return valueOf(v);
    }

}
