//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.data_marking.extensions.markingstructure;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.mitre.data_marking.marking_1.MarkingStructureType;


/**
 * Nodes may be marked by multiple TLP Marking statements. When this occurs, the node should be considered marked at the most restrictive TLP Marking of all TLP Markings that were applied to it. For example, if a node is marked both GREEN and AMBER, the node should be considered AMBER.
 * 
 * <p>Java class for TLPMarkingStructureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TLPMarkingStructureType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://data-marking.mitre.org/Marking-1}MarkingStructureType">
 *       &lt;attribute name="color" type="{http://data-marking.mitre.org/extensions/MarkingStructure#TLP-1}TLPColorEnum" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TLPMarkingStructureType")
public class TLPMarkingStructureType
    extends MarkingStructureType
{

    @XmlAttribute(name = "color")
    protected TLPColorEnum color;

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link TLPColorEnum }
     *     
     */
    public TLPColorEnum getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLPColorEnum }
     *     
     */
    public void setColor(TLPColorEnum value) {
        this.color = value;
    }

}
