//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.stix.extensions.ap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The CAPECInstanceType provides an extension to the APStructureAbstractType which imports and leverages the CAPEC 2.7 schema for structured characterization of Attack Patterns.
 * 
 * <p>Java class for CAPEC2.7InstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CAPEC2.7InstanceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://stix.mitre.org/TTP-1}AttackPatternType">
 *       &lt;sequence>
 *         &lt;element name="CAPEC" type="{http://capec.mitre.org/capec-2}Attack_PatternType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CAPEC2.7InstanceType", propOrder = {
    "capec"
})
public class CAPEC27InstanceType
    extends org.mitre.stix.ttp_1.AttackPatternType
{

    @XmlElement(name = "CAPEC", required = true)
    protected org.mitre.capec.capec_2.AttackPatternType capec;

    /**
     * Gets the value of the capec property.
     * 
     * @return
     *     possible object is
     *     {@link org.mitre.capec.capec_2.AttackPatternType }
     *     
     */
    public org.mitre.capec.capec_2.AttackPatternType getCAPEC() {
        return capec;
    }

    /**
     * Sets the value of the capec property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.mitre.capec.capec_2.AttackPatternType }
     *     
     */
    public void setCAPEC(org.mitre.capec.capec_2.AttackPatternType value) {
        this.capec = value;
    }

}
