//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * The AccessedFileListType specifies a list of files accessed by a prefetch application.
 * 
 * <p>Java class for AccessedFileListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessedFileListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Accessed_Filename" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessedFileListType", namespace = "http://cybox.mitre.org/objects#WinPrefetchObject-2", propOrder = {
    "accessedFilename"
})
public class AccessedFileListType {

    @XmlElement(name = "Accessed_Filename", required = true)
    protected List<StringObjectPropertyType> accessedFilename;

    /**
     * Gets the value of the accessedFilename property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessedFilename property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessedFilename().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringObjectPropertyType }
     * 
     * 
     */
    public List<StringObjectPropertyType> getAccessedFilename() {
        if (accessedFilename == null) {
            accessedFilename = new ArrayList<StringObjectPropertyType>();
        }
        return this.accessedFilename;
    }

}
