//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.ObjectPropertiesType;


/**
 * The ARPCacheObjectType type is intended to characterize entries in a system's address resolution protocol (ARP) cache.
 * 
 * <p>Java class for ARPCacheObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ARPCacheObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/common-2}ObjectPropertiesType">
 *       &lt;sequence>
 *         &lt;element name="ARP_Cache_Entry" type="{http://cybox.mitre.org/objects#ARPCacheObject-1}ARPCacheEntryType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ARPCacheObjectType", namespace = "http://cybox.mitre.org/objects#ARPCacheObject-1", propOrder = {
    "arpCacheEntry"
})
public class ARPCacheObjectType
    extends ObjectPropertiesType
{

    @XmlElement(name = "ARP_Cache_Entry", required = true)
    protected List<ARPCacheEntryType> arpCacheEntry;

    /**
     * Gets the value of the arpCacheEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arpCacheEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getARPCacheEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ARPCacheEntryType }
     * 
     * 
     */
    public List<ARPCacheEntryType> getARPCacheEntry() {
        if (arpCacheEntry == null) {
            arpCacheEntry = new ArrayList<ARPCacheEntryType>();
        }
        return this.arpCacheEntry;
    }

}
