//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.IntegerObjectPropertyType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * Specifies the fields in an Options Template Record Field Specifier, as explained in RFC 5101, sections 3.2 and 3.4.2.2. It consists of two sequences: Scope Fields and Option Fields, appended together.
 * 
 * <p>Java class for IPFIXOptionsTemplateRecordFieldSpecifiersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPFIXOptionsTemplateRecordFieldSpecifiersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="Scope_Enterprise_Bit" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *           &lt;element name="Scope_Information_Element_ID" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *           &lt;element name="Scope_Field_Length" type="{http://cybox.mitre.org/common-2}IntegerObjectPropertyType" minOccurs="0"/>
 *           &lt;element name="Scope_Enterprise_Number" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="Option_Enterprise_Bit" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *           &lt;element name="Option_Information_Element_ID" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *           &lt;element name="Option_Field_Length" type="{http://cybox.mitre.org/common-2}IntegerObjectPropertyType" minOccurs="0"/>
 *           &lt;element name="Option_Enterprise_Number" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPFIXOptionsTemplateRecordFieldSpecifiersType", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", propOrder = {
    "scopeEnterpriseBitAndScopeInformationElementIDAndScopeFieldLength",
    "optionEnterpriseBitAndOptionInformationElementIDAndOptionFieldLength"
})
public class IPFIXOptionsTemplateRecordFieldSpecifiersType {

    @XmlElementRefs({
        @XmlElementRef(name = "Scope_Enterprise_Number", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Scope_Field_Length", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Scope_Enterprise_Bit", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Scope_Information_Element_ID", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> scopeEnterpriseBitAndScopeInformationElementIDAndScopeFieldLength;
    @XmlElementRefs({
        @XmlElementRef(name = "Option_Enterprise_Bit", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Option_Information_Element_ID", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Option_Enterprise_Number", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Option_Field_Length", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> optionEnterpriseBitAndOptionInformationElementIDAndOptionFieldLength;

    /**
     * Gets the value of the scopeEnterpriseBitAndScopeInformationElementIDAndScopeFieldLength property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scopeEnterpriseBitAndScopeInformationElementIDAndScopeFieldLength property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScopeEnterpriseBitAndScopeInformationElementIDAndScopeFieldLength().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link StringObjectPropertyType }{@code >}
     * {@link JAXBElement }{@code <}{@link IntegerObjectPropertyType }{@code >}
     * {@link JAXBElement }{@code <}{@link StringObjectPropertyType }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getScopeEnterpriseBitAndScopeInformationElementIDAndScopeFieldLength() {
        if (scopeEnterpriseBitAndScopeInformationElementIDAndScopeFieldLength == null) {
            scopeEnterpriseBitAndScopeInformationElementIDAndScopeFieldLength = new ArrayList<JAXBElement<?>>();
        }
        return this.scopeEnterpriseBitAndScopeInformationElementIDAndScopeFieldLength;
    }

    /**
     * Gets the value of the optionEnterpriseBitAndOptionInformationElementIDAndOptionFieldLength property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionEnterpriseBitAndOptionInformationElementIDAndOptionFieldLength property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionEnterpriseBitAndOptionInformationElementIDAndOptionFieldLength().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link StringObjectPropertyType }{@code >}
     * {@link JAXBElement }{@code <}{@link StringObjectPropertyType }{@code >}
     * {@link JAXBElement }{@code <}{@link IntegerObjectPropertyType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getOptionEnterpriseBitAndOptionInformationElementIDAndOptionFieldLength() {
        if (optionEnterpriseBitAndOptionInformationElementIDAndOptionFieldLength == null) {
            optionEnterpriseBitAndOptionInformationElementIDAndOptionFieldLength = new ArrayList<JAXBElement<?>>();
        }
        return this.optionEnterpriseBitAndOptionInformationElementIDAndOptionFieldLength;
    }

}
