//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * The Link Object is intended to characterize links, such as those on a webpage or in an e-mail message.
 * 
 * <p>Java class for LinkObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinkObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/objects#URIObject-2}URIObjectType">
 *       &lt;sequence>
 *         &lt;element name="URL_Label" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinkObjectType", namespace = "http://cybox.mitre.org/objects#LinkObject-1", propOrder = {
    "urlLabel"
})
public class LinkObjectType
    extends URIObjectType
{

    @XmlElement(name = "URL_Label")
    protected StringObjectPropertyType urlLabel;

    /**
     * Gets the value of the urlLabel property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getURLLabel() {
        return urlLabel;
    }

    /**
     * Sets the value of the urlLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setURLLabel(StringObjectPropertyType value) {
        this.urlLabel = value;
    }

}
