//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.HexBinaryObjectPropertyType;
import org.mitre.cybox.common_2.IntegerObjectPropertyType;


/**
 * Specifies a Data FlowSet, which is one or more records, of the same type, that are grouped together in an Export Packet. Each record is either a Flow Data Record or an Options Data Record previously defined by a Template Record or an Options Template Record. http://www.ietf.org/rfc/rfc3954.txt.
 * 
 * <p>Java class for NetflowV9DataFlowSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetflowV9DataFlowSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Flow_Set_ID_Template_ID" type="{http://cybox.mitre.org/common-2}IntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Length" type="{http://cybox.mitre.org/common-2}IntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Data_Record" type="{http://cybox.mitre.org/objects#NetworkFlowObject-2}NetflowV9DataRecordType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Padding" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetflowV9DataFlowSetType", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", propOrder = {
    "flowSetIDTemplateID",
    "length",
    "dataRecord",
    "padding"
})
public class NetflowV9DataFlowSetType {

    @XmlElement(name = "Flow_Set_ID_Template_ID")
    protected IntegerObjectPropertyType flowSetIDTemplateID;
    @XmlElement(name = "Length")
    protected IntegerObjectPropertyType length;
    @XmlElement(name = "Data_Record")
    protected List<NetflowV9DataRecordType> dataRecord;
    @XmlElement(name = "Padding")
    protected HexBinaryObjectPropertyType padding;

    /**
     * Gets the value of the flowSetIDTemplateID property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public IntegerObjectPropertyType getFlowSetIDTemplateID() {
        return flowSetIDTemplateID;
    }

    /**
     * Sets the value of the flowSetIDTemplateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public void setFlowSetIDTemplateID(IntegerObjectPropertyType value) {
        this.flowSetIDTemplateID = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public IntegerObjectPropertyType getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public void setLength(IntegerObjectPropertyType value) {
        this.length = value;
    }

    /**
     * Gets the value of the dataRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetflowV9DataRecordType }
     * 
     * 
     */
    public List<NetflowV9DataRecordType> getDataRecord() {
        if (dataRecord == null) {
            dataRecord = new ArrayList<NetflowV9DataRecordType>();
        }
        return this.dataRecord;
    }

    /**
     * Gets the value of the padding property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getPadding() {
        return padding;
    }

    /**
     * Sets the value of the padding property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setPadding(HexBinaryObjectPropertyType value) {
        this.padding = value;
    }

}
