//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The NetworkRouteEntriesType type is intended to characterize the set of network route segments for this route.
 * 
 * <p>Java class for NetworkRouteEntriesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkRouteEntriesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Network_Route_Entry" type="{http://cybox.mitre.org/objects#NetworkRouteEntryObject-2}NetworkRouteEntryObjectType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkRouteEntriesType", namespace = "http://cybox.mitre.org/objects#NetworkRouteObject-2", propOrder = {
    "networkRouteEntry"
})
public class NetworkRouteEntriesType {

    @XmlElement(name = "Network_Route_Entry")
    protected List<NetworkRouteEntryObjectType> networkRouteEntry;

    /**
     * Gets the value of the networkRouteEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the networkRouteEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkRouteEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkRouteEntryObjectType }
     * 
     * 
     */
    public List<NetworkRouteEntryObjectType> getNetworkRouteEntry() {
        if (networkRouteEntry == null) {
            networkRouteEntry = new ArrayList<NetworkRouteEntryObjectType>();
        }
        return this.networkRouteEntry;
    }

}
