//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * The PackagingType captures any packaging layers applied to an artifact.
 * 
 * <p>Java class for PackagingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackagingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="Compression" type="{http://cybox.mitre.org/objects#ArtifactObject-2}CompressionType" minOccurs="0"/>
 *           &lt;element name="Encryption" type="{http://cybox.mitre.org/objects#ArtifactObject-2}EncryptionType" minOccurs="0"/>
 *           &lt;element name="Encoding" type="{http://cybox.mitre.org/objects#ArtifactObject-2}EncodingType" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="is_encrypted" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="is_compressed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackagingType", namespace = "http://cybox.mitre.org/objects#ArtifactObject-2", propOrder = {
    "compressionOrEncryptionOrEncoding"
})
public class PackagingType {

    @XmlElements({
        @XmlElement(name = "Compression", type = CompressionType.class),
        @XmlElement(name = "Encryption", type = EncryptionType.class),
        @XmlElement(name = "Encoding", type = EncodingType.class)
    })
    protected List<Object> compressionOrEncryptionOrEncoding;
    @XmlAttribute(name = "is_encrypted")
    protected Boolean isEncrypted;
    @XmlAttribute(name = "is_compressed")
    protected Boolean isCompressed;

    /**
     * Gets the value of the compressionOrEncryptionOrEncoding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compressionOrEncryptionOrEncoding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompressionOrEncryptionOrEncoding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompressionType }
     * {@link EncryptionType }
     * {@link EncodingType }
     * 
     * 
     */
    public List<Object> getCompressionOrEncryptionOrEncoding() {
        if (compressionOrEncryptionOrEncoding == null) {
            compressionOrEncryptionOrEncoding = new ArrayList<Object>();
        }
        return this.compressionOrEncryptionOrEncoding;
    }

    /**
     * Gets the value of the isEncrypted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEncrypted() {
        return isEncrypted;
    }

    /**
     * Sets the value of the isEncrypted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEncrypted(Boolean value) {
        this.isEncrypted = value;
    }

    /**
     * Gets the value of the isCompressed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCompressed() {
        return isCompressed;
    }

    /**
     * Sets the value of the isCompressed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCompressed(Boolean value) {
        this.isCompressed = value;
    }

}
