//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The PDFXrefEntryListType captures a list of cross-reference table subsection entries.
 * 
 * <p>Java class for PDFXrefEntryListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PDFXrefEntryListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cross_Reference_Entry" type="{http://cybox.mitre.org/objects#PDFFileObject-1}PDFXrefEntryType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PDFXrefEntryListType", namespace = "http://cybox.mitre.org/objects#PDFFileObject-1", propOrder = {
    "crossReferenceEntry"
})
public class PDFXrefEntryListType {

    @XmlElement(name = "Cross_Reference_Entry", required = true)
    protected List<PDFXrefEntryType> crossReferenceEntry;

    /**
     * Gets the value of the crossReferenceEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crossReferenceEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrossReferenceEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PDFXrefEntryType }
     * 
     * 
     */
    public List<PDFXrefEntryType> getCrossReferenceEntry() {
        if (crossReferenceEntry == null) {
            crossReferenceEntry = new ArrayList<PDFXrefEntryType>();
        }
        return this.crossReferenceEntry;
    }

}
