//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * only UDP and TCP defined to begin. Other protocols will be defined as necessary.
 * 
 * <p>Java class for TransportLayerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportLayerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="TCP" type="{http://cybox.mitre.org/objects#PacketObject-2}TCPType" minOccurs="0"/>
 *         &lt;element name="UDP" type="{http://cybox.mitre.org/objects#PacketObject-2}UDPType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportLayerType", propOrder = {
    "tcp",
    "udp"
})
public class TransportLayerType {

    @XmlElement(name = "TCP")
    protected TCPType tcp;
    @XmlElement(name = "UDP")
    protected UDPType udp;

    /**
     * Gets the value of the tcp property.
     * 
     * @return
     *     possible object is
     *     {@link TCPType }
     *     
     */
    public TCPType getTCP() {
        return tcp;
    }

    /**
     * Sets the value of the tcp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCPType }
     *     
     */
    public void setTCP(TCPType value) {
        this.tcp = value;
    }

    /**
     * Gets the value of the udp property.
     * 
     * @return
     *     possible object is
     *     {@link UDPType }
     *     
     */
    public UDPType getUDP() {
        return udp;
    }

    /**
     * Sets the value of the udp property.
     * 
     * @param value
     *     allowed object is
     *     {@link UDPType }
     *     
     */
    public void setUDP(UDPType value) {
        this.udp = value;
    }

}
