//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.HexBinaryObjectPropertyType;


/**
 *  0-1500 then it is a length field. Otherwise, it defines the protocol type of the Internet layer.
 * 
 * <p>Java class for TypeLengthType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeLengthType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Length" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Internet_Layer_Type" type="{http://cybox.mitre.org/objects#PacketObject-2}IANAEtherType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeLengthType", propOrder = {
    "length",
    "internetLayerType"
})
public class TypeLengthType {

    @XmlElement(name = "Length")
    protected HexBinaryObjectPropertyType length;
    @XmlElement(name = "Internet_Layer_Type")
    protected IANAEtherType internetLayerType;

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setLength(HexBinaryObjectPropertyType value) {
        this.length = value;
    }

    /**
     * Gets the value of the internetLayerType property.
     * 
     * @return
     *     possible object is
     *     {@link IANAEtherType }
     *     
     */
    public IANAEtherType getInternetLayerType() {
        return internetLayerType;
    }

    /**
     * Sets the value of the internetLayerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IANAEtherType }
     *     
     */
    public void setInternetLayerType(IANAEtherType value) {
        this.internetLayerType = value;
    }

}
