//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.ObjectPropertiesType;
import org.mitre.cybox.common_2.ToolInformationType;


/**
 * The URLHistoryObject type is intended to characterize the stored URL history for a particular web browser.
 * 
 * <p>Java class for URLHistoryObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="URLHistoryObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/common-2}ObjectPropertiesType">
 *       &lt;sequence>
 *         &lt;element name="Browser_Information" type="{http://cybox.mitre.org/common-2}ToolInformationType" minOccurs="0"/>
 *         &lt;element name="URL_History_Entry" type="{http://cybox.mitre.org/objects#URLHistoryObject-1}URLHistoryEntryType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "URLHistoryObjectType", namespace = "http://cybox.mitre.org/objects#URLHistoryObject-1", propOrder = {
    "browserInformation",
    "urlHistoryEntry"
})
public class URLHistoryObjectType
    extends ObjectPropertiesType
{

    @XmlElement(name = "Browser_Information")
    protected ToolInformationType browserInformation;
    @XmlElement(name = "URL_History_Entry")
    protected List<URLHistoryEntryType> urlHistoryEntry;

    /**
     * Gets the value of the browserInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ToolInformationType }
     *     
     */
    public ToolInformationType getBrowserInformation() {
        return browserInformation;
    }

    /**
     * Sets the value of the browserInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolInformationType }
     *     
     */
    public void setBrowserInformation(ToolInformationType value) {
        this.browserInformation = value;
    }

    /**
     * Gets the value of the urlHistoryEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the urlHistoryEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getURLHistoryEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link URLHistoryEntryType }
     * 
     * 
     */
    public List<URLHistoryEntryType> getURLHistoryEntry() {
        if (urlHistoryEntry == null) {
            urlHistoryEntry = new ArrayList<URLHistoryEntryType>();
        }
        return this.urlHistoryEntry;
    }

}
