//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.17 at 04:06:30 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The WindowsNetworkRouteEntryObjectType type is intended to characterize Windows network routing table entries.
 * 
 * <p>Java class for WindowsNetworkRouteEntryObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WindowsNetworkRouteEntryObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/objects#NetworkRouteEntryObject-2}NetworkRouteEntryObjectType">
 *       &lt;sequence>
 *         &lt;element name="NL_ROUTE_PROTOCOL" type="{http://cybox.mitre.org/objects#WinNetworkRouteEntryObject-2}NLRouteProtocolType" minOccurs="0"/>
 *         &lt;element name="NL_ROUTE_ORIGIN" type="{http://cybox.mitre.org/objects#WinNetworkRouteEntryObject-2}NLRouteOriginType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WindowsNetworkRouteEntryObjectType", namespace = "http://cybox.mitre.org/objects#WinNetworkRouteEntryObject-2", propOrder = {
    "nlrouteprotocol",
    "nlrouteorigin"
})
public class WindowsNetworkRouteEntryObjectType
    extends NetworkRouteEntryObjectType
{

    @XmlElement(name = "NL_ROUTE_PROTOCOL")
    protected NLRouteProtocolType nlrouteprotocol;
    @XmlElement(name = "NL_ROUTE_ORIGIN")
    protected NLRouteOriginType nlrouteorigin;

    /**
     * Gets the value of the nlrouteprotocol property.
     * 
     * @return
     *     possible object is
     *     {@link NLRouteProtocolType }
     *     
     */
    public NLRouteProtocolType getNLROUTEPROTOCOL() {
        return nlrouteprotocol;
    }

    /**
     * Sets the value of the nlrouteprotocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link NLRouteProtocolType }
     *     
     */
    public void setNLROUTEPROTOCOL(NLRouteProtocolType value) {
        this.nlrouteprotocol = value;
    }

    /**
     * Gets the value of the nlrouteorigin property.
     * 
     * @return
     *     possible object is
     *     {@link NLRouteOriginType }
     *     
     */
    public NLRouteOriginType getNLROUTEORIGIN() {
        return nlrouteorigin;
    }

    /**
     * Sets the value of the nlrouteorigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link NLRouteOriginType }
     *     
     */
    public void setNLROUTEORIGIN(NLRouteOriginType value) {
        this.nlrouteorigin = value;
    }

}
